using System.Text;

namespace MigrationTool.Domain;

public static class CreateTableUpdateScriptBuilder
{
    public static string Build(
        DatabaseProviderKind provider,
        string schema,
        string table,
        IReadOnlyList<CreateTableColumn> missingColumns,
        IReadOnlyCollection<string> sourceColumns,
        IReadOnlyCollection<string> liveColumns)
    {
        var qualified = $"{SqlIdentifier.Quote(provider, schema)}.{SqlIdentifier.Quote(provider, table)}";
        var builder = new StringBuilder();
        builder.AppendLine($"-- Update script for {qualified}");
        builder.AppendLine("-- Generated by comparing CREATE TABLE source columns to the live table.");
        builder.AppendLine("-- Additive only: missing columns are added. Existing columns are not dropped or rewritten.");
        builder.AppendLine($"-- Source columns: {string.Join(", ", sourceColumns)}");
        builder.AppendLine(
            $"-- Live columns: {(liveColumns.Count == 0 ? "(none)" : string.Join(", ", liveColumns))}");
        builder.AppendLine(
            $"-- Columns to add: {(missingColumns.Count == 0 ? "(none)" : string.Join(", ", missingColumns.Select(column => column.Name)))}");
        builder.AppendLine();

        if (missingColumns.Count == 0)
        {
            builder.AppendLine("-- No ALTER statements required.");
            return builder.ToString();
        }

        foreach (var column in missingColumns)
        {
            builder.AppendLine(AlterScriptBuilder.Build(
                provider,
                schema,
                table,
                column,
                "taken from CREATE TABLE source").TrimEnd());
            builder.AppendLine();
        }

        return builder.ToString().TrimEnd() + Environment.NewLine;
    }

    public static string FileName(string schema, string table) =>
        $"update_{Safe(schema)}_{Safe(table)}.sql";

    private static string Safe(string value)
    {
        var chars = value.Select(ch => char.IsLetterOrDigit(ch) ? ch : '_').ToArray();
        var safe = new string(chars).Trim('_');
        return safe.Length == 0 ? "object" : safe;
    }
}
