using System.Text;

namespace FindingsMigration.Core;

/// <summary>
/// Writes a minimal xUnit reconciliation test template referencing
/// <c>Tests/Reconciliation.Tests</c> / Showcase shadow patterns.
/// </summary>
public sealed class ReconciliationTestStubGenerator
{
    public ReconciliationTestStubResult Write(
        string outputDirectory,
        string domainName,
        string serviceName)
    {
        if (string.IsNullOrWhiteSpace(serviceName))
            throw new ArgumentException("Service name is required.", nameof(serviceName));

        var testsDir = ResolveTestsDirectory(outputDirectory, serviceName);
        Directory.CreateDirectory(testsDir);

        var className = $"{SanitizeIdentifier(domainName)}ShadowReconciliationStubTests";
        var path = Path.Combine(testsDir, $"{className}.cs");
        File.WriteAllText(path, BuildTemplate(serviceName, domainName, className), Encoding.UTF8);

        return new ReconciliationTestStubResult
        {
            WrittenFiles = [path],
            TestsDirectory = testsDir
        };
    }

    /// <summary>
    /// Prefer <c>{service}.Tests</c> under a service root; otherwise write under <c>out/Tests</c>.
    /// </summary>
    public static string ResolveTestsDirectory(string outputOrServiceRoot, string serviceName)
    {
        var dedicated = Path.Combine(outputOrServiceRoot, $"{serviceName}.Tests");
        if (Directory.Exists(dedicated) || Directory.Exists(Path.Combine(outputOrServiceRoot, $"{serviceName}.Api")))
            return dedicated;

        var sibling = Path.Combine(outputOrServiceRoot, "..", $"{serviceName}.Tests");
        var siblingFull = Path.GetFullPath(sibling);
        if (Directory.Exists(siblingFull))
            return siblingFull;

        return Path.Combine(outputOrServiceRoot, "Tests");
    }

    private static string BuildTemplate(string serviceName, string domainName, string className) =>
        $$"""
        // <auto-generated stub />
        // FindingsMigration reconciliation template — wire to BuildingBlocks.Migration shadow compare
        // and kit Tests/Reconciliation.Tests patterns (see ShowcaseDataService.Tests/ShadowReconciliationTests).
        // Does not invent credentials or hit production SQL.
        using Xunit;

        namespace {{serviceName}}.Tests;

        /// <summary>
        /// Stub for {{domainName}} shadow-read / reconciliation checks.
        /// Replace MismatchAccess-style fakes with domain ports after packaging approval.
        /// Pattern: Shadow route → compare Source vs Owned payloads → assert dashboard counters.
        /// </summary>
        public class {{className}}
        {
            [Fact(Skip = "Stub — implement after domain package ownership approval")]
            public void Shadow_Mismatch_IsVisibleOnDashboard()
            {
                // TODO: mirror ShowcaseDataService.Tests.ShadowReconciliationTests
                // 1. Configure MigrationRoutingOptions.DefaultRoute = DataAccessRoute.Shadow
                // 2. Drive a read that returns different Source vs Owned payloads
                // 3. Assert dashboard ShadowComparisons / MismatchingShadows
                Assert.True(true);
            }

            [Fact(Skip = "Stub — implement ResultSetComparison when cutover wave is planned")]
            public void Reconciliation_ResultSets_Match_WhenOwnedAligned()
            {
                // TODO: align with Tests/Reconciliation.Tests once package versions are wired
                Assert.True(true);
            }
        }
        """;

    private static string SanitizeIdentifier(string name)
    {
        var chars = name.Where(char.IsLetterOrDigit).ToArray();
        if (chars.Length == 0) return "Domain";
        var s = new string(chars);
        return char.ToUpperInvariant(s[0]) + s[1..];
    }
}

public sealed class ReconciliationTestStubResult
{
    public List<string> WrittenFiles { get; init; } = [];
    public string TestsDirectory { get; init; } = "";
}
