using System.Text;
using System.Text.RegularExpressions;
using FindingsMigration.Contracts;

namespace FindingsMigration.Core;

/// <summary>
/// Emits SQL stubs and Dapper SP wrappers from stored-procedure-map.json into a scaffolded DataService.
/// </summary>
public sealed class SpWrapperGenerator
{
    public SpGenerationResult Generate(
        StoredProcedureMapDocument spMap,
        string serviceRoot,
        string domainName,
        string targetSchema,
        string serviceName)
    {
        var schema = string.IsNullOrWhiteSpace(targetSchema)
            ? domainName.ToLowerInvariant()
            : targetSchema;

        var sqlDir = Path.Combine(serviceRoot, $"{serviceName}.Database", "Programmability", "Generated");
        var csDir = Path.Combine(serviceRoot, $"{serviceName}.Infrastructure", "StoredProcedures", "Generated");
        Directory.CreateDirectory(sqlDir);
        Directory.CreateDirectory(csDir);

        var written = new List<string>();
        foreach (var proc in spMap.Procedures)
        {
            if (string.IsNullOrWhiteSpace(proc.Name)) continue;
            var safeName = SanitizeIdentifier(proc.Name);
            var sqlName = $"{schema}.{proc.Name}";
            var className = $"Sp_{safeName}";
            var interfaceName = $"I{className}";

            var sqlPath = Path.Combine(sqlDir, $"{safeName}.sql");
            File.WriteAllText(sqlPath, BuildSqlStub(schema, proc), Encoding.UTF8);
            written.Add(sqlPath);

            var csPath = Path.Combine(csDir, $"{className}.cs");
            File.WriteAllText(csPath, BuildWrapper(serviceName, schema, proc, className, interfaceName, sqlName), Encoding.UTF8);
            written.Add(csPath);
        }

        var scaffoldNote = Path.Combine(serviceRoot, "SP-GENERATED.md");
        File.WriteAllText(scaffoldNote, BuildNote(domainName, serviceName, spMap, written), Encoding.UTF8);
        written.Add(scaffoldNote);

        return new SpGenerationResult
        {
            ProcedureCount = spMap.Procedures.Count(p => !string.IsNullOrWhiteSpace(p.Name)),
            WrittenFiles = written
        };
    }

    public SpGenerationResult GenerateFromMapFile(
        string storedProcedureMapPath,
        string serviceRoot,
        string domainName,
        string targetSchema,
        string serviceName)
    {
        if (!File.Exists(storedProcedureMapPath))
            throw new FileNotFoundException("stored-procedure map not found", storedProcedureMapPath);

        var spMap = System.Text.Json.JsonSerializer.Deserialize<StoredProcedureMapDocument>(
            File.ReadAllText(storedProcedureMapPath),
            new System.Text.Json.JsonSerializerOptions { PropertyNameCaseInsensitive = true })
            ?? new StoredProcedureMapDocument();

        return Generate(spMap, serviceRoot, domainName, targetSchema, serviceName);
    }

    private static string BuildSqlStub(string schema, StoredProcedureEntry proc)
    {
        var reads = proc.Reads.Count == 0 ? "TBD" : string.Join(", ", proc.Reads);
        var writes = proc.Writes.Count == 0 ? "none" : string.Join(", ", proc.Writes);
        var callers = proc.Callers.Count == 0 ? "unknown" : string.Join(", ", proc.Callers);
        return $"""
            -- Generated stub from FindingsMigration (FacadeThenMove). DBA must review before deploy.
            -- Source callers: {callers}
            -- Tables read: {reads}
            -- Tables written: {writes}
            CREATE OR ALTER PROCEDURE [{schema}].[{proc.Name}]
            AS
            BEGIN
                SET NOCOUNT ON;
                -- TODO: migrate body from monolith SP, or keep façade on source until Owned cutover.
                RAISERROR('Stub only — not for production.', 16, 1);
            END
            GO
            """;
    }

    private static string BuildWrapper(
        string serviceName,
        string schema,
        StoredProcedureEntry proc,
        string className,
        string interfaceName,
        string sqlName)
    {
        return $$"""
            // <auto-generated />
            // FindingsMigration SP wrapper — fluent ExecuteSp<T>().ToListAsync() / ExecuteAsync.
            using BuildingBlocks.DataAccess.Abstractions;

            namespace {{serviceName}}.Infrastructure.StoredProcedures.Generated;

            public interface {{interfaceName}}
            {
                Task<int> ExecuteAsync(string connectionName, CancellationToken cancellationToken = default);
            }

            public sealed class {{className}} : {{interfaceName}}
            {
                public const string ProcedureName = "{{sqlName}}";
                private readonly IDataAccessContext _access;

                public {{className}}(IDataAccessContext access) => _access = access;

                public Task<int> ExecuteAsync(string connectionName, CancellationToken cancellationToken = default) =>
                    _access.ExecuteSp<object>(ProcedureName)
                        .On(connectionName)
                        .Named(ProcedureName)
                        .ExecuteAsync(cancellationToken);
            }
            """;
    }

    private static string BuildNote(string domain, string service, StoredProcedureMapDocument spMap, List<string> written)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# Generated SP wrappers — {domain}");
        sb.AppendLine();
        sb.AppendLine("Runtime modes (Showcase golden template):");
        sb.AppendLine("- `SourceFacade` / Blue — call source monolith connection");
        sb.AppendLine("- `Owned` / Green — call target owned DB");
        sb.AppendLine("- `Shadow` — compare both on reads; never dual-write");
        sb.AppendLine();
        sb.AppendLine("## Procedures");
        sb.AppendLine();
        foreach (var p in spMap.Procedures)
        {
            sb.AppendLine($"- `{p.Schema}.{p.Name}` callers: {string.Join(", ", p.Callers)}");
        }
        sb.AppendLine();
        sb.AppendLine("## Files");
        sb.AppendLine();
        foreach (var f in written)
            sb.AppendLine($"- `{f}`");
        sb.AppendLine();
        sb.AppendLine("Register generated wrappers in Infrastructure DI and keep SQL project ownership separate from EF.");
        return sb.ToString();
    }

    private static string SanitizeIdentifier(string name)
    {
        var cleaned = Regex.Replace(name, @"[^A-Za-z0-9_]", "_");
        if (cleaned.Length == 0) return "Proc";
        if (char.IsDigit(cleaned[0])) cleaned = "_" + cleaned;
        return cleaned;
    }
}

public sealed class SpGenerationResult
{
    public int ProcedureCount { get; init; }
    public List<string> WrittenFiles { get; init; } = [];
}
