using System.Security.Cryptography;
using System.Text;
using FindingsMigration.Contracts;

namespace FindingsMigration.Core;

/// <summary>
/// Emits additive SQL project stubs (hash placeholder + ownership comment only) —
/// does not move real definitions from the monolith.
/// </summary>
public sealed class SqlProjectSliceGenerator
{
    public SqlProjectSliceResult Generate(
        IEnumerable<string> objects,
        string outputDirectory,
        string schema,
        string serviceName,
        string? ownerTeam = null)
    {
        if (string.IsNullOrWhiteSpace(schema))
            throw new ArgumentException("Schema is required.", nameof(schema));
        if (string.IsNullOrWhiteSpace(serviceName))
            throw new ArgumentException("Service name is required.", nameof(serviceName));

        var list = objects
            .Select(o => o.Trim())
            .Where(o => o.Length > 0)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(o => o, StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (list.Count == 0)
            throw new ArgumentException("At least one object name is required.", nameof(objects));

        Directory.CreateDirectory(outputDirectory);
        var sqlDir = Path.Combine(outputDirectory, "sql");
        Directory.CreateDirectory(sqlDir);

        var written = new List<string>();
        foreach (var obj in list)
        {
            var leaf = obj.Contains('.') ? obj.Split('.').Last() : obj;
            var safe = SanitizeFileToken(leaf);
            var sqlPath = Path.Combine(sqlDir, $"{safe}.sql");
            var placeholderHash = ComputePlaceholderHash(schema, obj, serviceName);
            File.WriteAllText(sqlPath, BuildSqlStub(schema, leaf, obj, serviceName, placeholderHash), Encoding.UTF8);
            written.Add(sqlPath);
        }

        var ownershipPath = Path.Combine(outputDirectory, "ownership.yml");
        File.WriteAllText(
            ownershipPath,
            BuildOwnershipYaml(schema, serviceName, ownerTeam ?? "TBD", list),
            Encoding.UTF8);
        written.Add(ownershipPath);

        return new SqlProjectSliceResult
        {
            ObjectCount = list.Count,
            WrittenFiles = written
        };
    }

    public SqlProjectSliceResult GenerateFromCommaList(
        string commaSeparatedObjects,
        string outputDirectory,
        string schema,
        string serviceName,
        string? ownerTeam = null) =>
        Generate(
            commaSeparatedObjects.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries),
            outputDirectory,
            schema,
            serviceName,
            ownerTeam);

    private static string BuildSqlStub(
        string schema,
        string leaf,
        string fullObject,
        string service,
        string placeholderHash) =>
        $"""
        -- Ownership: {service} (SqlProject desired-state stub — additive only)
        -- Source object: {fullObject}
        -- DefinitionHashPlaceholder: {placeholderHash}
        -- DO NOT deploy as production DDL. Replace stub body after DBA-approved move from monolith.
        -- This file intentionally does not contain the real definition.

        -- PLACEHOLDER for [{schema}].[{leaf}]
        -- Real CREATE/ALTER belongs under human-reviewed cutover waves, not auto-generated here.
        """;

    private static string BuildOwnershipYaml(
        string schema,
        string service,
        string ownerTeam,
        List<string> objects)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by FindingsMigration SqlProjectSliceGenerator — review before committing.");
        sb.AppendLine($"target_service: {YamlEscape(service)}");
        sb.AppendLine($"target_schema: {YamlEscape(schema)}");
        sb.AppendLine($"owner_team: {YamlEscape(ownerTeam)}");
        sb.AppendLine("status: draft-slice");
        sb.AppendLine("requires_human_ownership_approval: true");
        sb.AppendLine("note: Stubs are hash+ownership only; definitions stay in monolith until approved.");
        sb.AppendLine("objects:");
        foreach (var o in objects)
            sb.AppendLine($"  - {YamlEscape(o)}");
        return sb.ToString();
    }

    private static string ComputePlaceholderHash(string schema, string obj, string service)
    {
        var bytes = Encoding.UTF8.GetBytes($"{schema}|{obj}|{service}|stub-v1");
        var hash = SHA256.HashData(bytes);
        return Convert.ToHexString(hash)[..16].ToLowerInvariant();
    }

    private static string SanitizeFileToken(string value)
    {
        var sb = new StringBuilder();
        foreach (var ch in value)
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '-');
        var s = sb.ToString().Trim('-');
        return string.IsNullOrEmpty(s) ? "object" : s.ToLowerInvariant();
    }

    private static string YamlEscape(string value) =>
        value.Contains(':') || value.Contains('#') || value.Contains('"') || value.Contains('\'')
            ? $"\"{value.Replace("\"", "\\\"")}\""
            : value;
}

public sealed class SqlProjectSliceResult
{
    public int ObjectCount { get; init; }
    public List<string> WrittenFiles { get; init; } = [];
}
